<?xml version="1.0" encoding="UTF-8"?><testrun name="stackTest" project="Stack Cucumber Example" tests="15" started="15" failures="2" errors="2" ignored="3">
  <testsuite name="com.qa.test.Guru99Test.stackTest" time="0.042">
    <testsuite name="Feature: Working with a Stack" time="0.042">
      <testsuite name="Scenario: Push an item into a stack" time="0.003">
        <testcase name="Given an empty stack" classname="Scenario: Push an item into a stack" time="0.001"/>
        <testcase name="When I push an item into the stack" classname="Scenario: Push an item into a stack" time="0.002"/>
        <testcase name="Then the stack contains one item" classname="Scenario: Push an item into a stack" time="0.0"/>
      </testsuite>
      <testsuite name="Scenario: Push two items into a stack" time="0.0">
        <testcase name="Given an empty stack" classname="Scenario: Push two items into a stack" time="0.0"/>
        <testcase name="When I push an item into the stack" classname="Scenario: Push two items into a stack" time="0.0"/>
        <testcase name="And I push another item into the stack" classname="Scenario: Push two items into a stack" time="0.0"/>
        <testcase name="Then the stack contains two items" classname="Scenario: Push two items into a stack" time="0.0"/>
      </testsuite>
      <testsuite name="Scenario: Pop a given item from the stack" time="0.0" incomplete="true">
        <failure>java.lang.AssertionError: expected:&lt;null&gt; but was:&lt;com.qa.test.Guru99Test.StackExample@76b1e9b8&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:834)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:144)&#13;
	at com.qa.test.Guru99Test.StackSteps.i_get_the_same_item_back(StackSteps.java:61)&#13;
	at ✽.Then I get the same item back(stack.feature:21)&#13;
&#13;
</failure>
        <testcase name="Given an empty stack" classname="Scenario: Pop a given item from the stack" time="0.0"/>
        <testcase name="When I push an item into the stack" classname="Scenario: Pop a given item from the stack" time="0.0"/>
        <testcase name="And I pop from the stack" classname="Scenario: Pop a given item from the stack" time="0.0"/>
        <testcase name="Then I get the same item back" classname="Scenario: Pop a given item from the stack" time="0.0">
          <failure>java.lang.AssertionError: expected:&lt;null&gt; but was:&lt;com.qa.test.Guru99Test.StackExample@76b1e9b8&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:834)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:144)&#13;
	at com.qa.test.Guru99Test.StackSteps.i_get_the_same_item_back(StackSteps.java:61)&#13;
	at ✽.Then I get the same item back(stack.feature:21)&#13;
&#13;
</failure>
        </testcase>
      </testsuite>
      <testsuite name="Scenario: Pop a given item from the stack" time="0.0" incomplete="true">
        <error>java.lang.NullPointerException&#13;
	at com.qa.test.Guru99Test.StackSteps.a_stack_with_items(StackSteps.java:68)&#13;
	at ✽.Given a stack with 3 items(stack.feature:24)&#13;
&#13;
</error>
        <testcase name="Given a stack with 3 items" classname="Scenario: Pop a given item from the stack" time="0.0">
          <error>java.lang.NullPointerException&#13;
	at com.qa.test.Guru99Test.StackSteps.a_stack_with_items(StackSteps.java:68)&#13;
	at ✽.Given a stack with 3 items(stack.feature:24)&#13;
&#13;
</error>
        </testcase>
        <testcase name="When I push an item into the stack" classname="Scenario: Pop a given item from the stack" time="0.0" ignored="true"/>
        <testcase name="And I pop from the stack" classname="Scenario: Pop a given item from the stack" time="0.0" ignored="true"/>
        <testcase name="Then I get the same item back" classname="Scenario: Pop a given item from the stack" time="0.0" ignored="true"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testrun>
